// Minimal PCB Course fixture for preview/demo mode
// This is a pre-built course that shows what AnyLearn looks like without an API key.
import type { Course } from './models';

export const pcbCourseFixture: Course = {
  id: 'demo-pcb-course',
  goal: 'I want to learn PCB design from zero and eventually design my own board',
  profile: {
    topic: 'PCB Design',
    endArtifact: 'Working PCB board',
    level: 'beginner',
    hoursPerWeek: 5,
  },
  version: 1,
  concepts: [
    { id: 'c-elec-basics', name: 'Electronic Fundamentals', summary: 'Voltage, current, resistance and Ohm\'s law.', prereqIDs: [] },
    { id: 'c-components', name: 'Basic Components', summary: 'Resistors, capacitors, LEDs, transistors.', prereqIDs: ['c-elec-basics'] },
    { id: 'c-schematic', name: 'Schematic Capture', summary: 'Reading and drawing circuit schematics.', prereqIDs: ['c-components'] },
    { id: 'c-pcb-basics', name: 'PCB Concepts', summary: 'Layers, traces, pads, vias and ground planes.', prereqIDs: ['c-schematic'] },
    { id: 'c-kicad', name: 'KiCad EDA Tool', summary: 'Using KiCad for schematic and PCB layout.', prereqIDs: ['c-pcb-basics'] },
    { id: 'c-layout', name: 'PCB Layout Rules', summary: 'Routing rules, clearances, and design for manufacturing.', prereqIDs: ['c-kicad'] },
    { id: 'c-gerbers', name: 'Gerber Files & Fab', summary: 'Exporting Gerbers and ordering from PCB fabricators.', prereqIDs: ['c-layout'] },
  ],
  modules: [
    {
      id: 'm-foundations',
      title: 'Electronics Foundations',
      outcome: 'Understand electricity and basic components',
      lessonIDs: ['l-elec-basics', 'l-components'],
    },
    {
      id: 'm-schematics',
      title: 'Schematic Design',
      outcome: 'Read and draw circuit schematics confidently',
      lessonIDs: ['l-schematic-reading', 'l-schematic-drawing'],
    },
    {
      id: 'm-pcb-layout',
      title: 'PCB Layout',
      outcome: 'Design a complete PCB layout in KiCad',
      lessonIDs: ['l-pcb-concepts', 'l-kicad-intro', 'l-routing'],
    },
    {
      id: 'm-fabrication',
      title: 'Fabrication & First Board',
      outcome: 'Order and receive your first PCB',
      lessonIDs: ['l-gerbers', 'l-bom', 'l-order'],
    },
  ],
  lessons: {
    'l-elec-basics': {
      id: 'l-elec-basics', moduleID: 'm-foundations',
      title: 'Voltage, Current & Resistance',
      conceptIDs: ['c-elec-basics'],
      objectives: ['Define voltage, current and resistance', 'Apply Ohm\'s law', 'Calculate power dissipation'],
      status: 'ready',
      blocks: [
        { type: 'markdown', id: 'b-hook-elec', markdown: '## Why electronics basics matter\n\nBefore you can design a PCB, you need to understand what\'s flowing through those copper traces. Think of electricity like water: **voltage** is the pressure, **current** is the flow rate, and **resistance** is how narrow the pipe is.' },
        { type: 'workedExample', id: 'b-example-elec', title: 'Calculating LED current', steps: [
          { text: 'Supply voltage: 5V. LED forward voltage: 2V. Desired current: 20mA.', why: 'LEDs need a specific current — too much and they burn out.' },
          { text: 'Voltage across resistor = 5V − 2V = 3V', why: 'The resistor drops whatever voltage the LED doesn\'t need.' },
          { text: 'R = V/I = 3V / 0.020A = 150Ω', why: 'Ohm\'s law gives us the resistor value.' },
        ]},
        { type: 'callout', id: 'b-mistakes-elec', kind: 'mistake', markdown: '**Common mistake:** Forgetting that LED current should be limited with a resistor. Connecting an LED directly to 5V will immediately burn it out.' },
        { type: 'checkpoint', id: 'b-check-elec', conceptID: 'c-elec-basics', question: 'A 12V supply powers a 100Ω resistor. What current flows?', answer: '120mA (I = V/R = 12/100)', hint: 'Use Ohm\'s law: I = V/R' },
      ],
      task: { title: 'Calculate resistor values', instructions: ['Open a simulator (falstad.com/circuit)', 'Build a simple LED circuit with 5V supply', 'Calculate and verify the correct resistor value'], successCriteria: ['LED lights up without burning', 'Correct current measurement'] },
      resourceQueries: ['ohms law explained beginner', 'electronics fundamentals tutorial'],
      resources: [],
      sources: [],
      unsourced: true,
      confidence: 'high',
      version: 1,
    },
    'l-components': {
      id: 'l-components', moduleID: 'm-foundations',
      title: 'Basic Electronic Components',
      conceptIDs: ['c-components'],
      objectives: ['Identify resistors, capacitors, LEDs, and transistors', 'Read component datasheets', 'Choose the right component for a job'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['electronic components explained', 'how to read datasheet beginner'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-schematic-reading': {
      id: 'l-schematic-reading', moduleID: 'm-schematics',
      title: 'Reading Schematics',
      conceptIDs: ['c-schematic'],
      objectives: ['Identify standard schematic symbols', 'Trace signal flow through a circuit', 'Find voltage references and grounds'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['how to read schematic diagram', 'schematic symbols guide'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-schematic-drawing': {
      id: 'l-schematic-drawing', moduleID: 'm-schematics',
      title: 'Drawing Schematics in KiCad',
      conceptIDs: ['c-schematic', 'c-kicad'],
      objectives: ['Create a new schematic project in KiCad', 'Place and wire components', 'Add power symbols and labels'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['kicad schematic tutorial beginner', 'kicad eeschema walkthrough'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-pcb-concepts': {
      id: 'l-pcb-concepts', moduleID: 'm-pcb-layout',
      title: 'PCB Layers & Concepts',
      conceptIDs: ['c-pcb-basics'],
      objectives: ['Explain copper layers, silkscreen, solder mask', 'Define trace, pad, via, and plane', 'Know when to use 2-layer vs 4-layer'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['pcb layer stackup explained', 'what is a via pcb'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-kicad-intro': {
      id: 'l-kicad-intro', moduleID: 'm-pcb-layout',
      title: 'KiCad PCB Editor',
      conceptIDs: ['c-kicad'],
      objectives: ['Navigate the KiCad PCB editor', 'Import netlist from schematic', 'Set board outline and design rules'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['kicad pcb editor tutorial', 'kicad design rules constraints'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-routing': {
      id: 'l-routing', moduleID: 'm-pcb-layout',
      title: 'Routing Traces & Ground Planes',
      conceptIDs: ['c-layout'],
      objectives: ['Route signal traces manually', 'Pour a copper ground plane', 'Verify design rule check passes'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['pcb routing best practices', 'ground plane pour kicad'],
      resources: [], sources: [], unsourced: true, confidence: 'medium', version: 1,
    },
    'l-gerbers': {
      id: 'l-gerbers', moduleID: 'm-fabrication',
      title: 'Exporting Gerber Files',
      conceptIDs: ['c-gerbers'],
      objectives: ['Generate Gerber files from KiCad', 'Verify files with GerbView', 'Prepare manufacturing package'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['export gerber kicad', 'gerber file check viewer'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-bom': {
      id: 'l-bom', moduleID: 'm-fabrication',
      title: 'Bill of Materials (BOM)',
      conceptIDs: ['c-gerbers'],
      objectives: ['Generate BOM from KiCad schematic', 'Source components from LCSC or DigiKey', 'Estimate project cost'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['kicad bom export', 'sourcing electronic components LCSC'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-order': {
      id: 'l-order', moduleID: 'm-fabrication',
      title: 'Ordering Your First PCB',
      conceptIDs: ['c-gerbers'],
      objectives: ['Upload Gerbers to JLCPCB or PCBWay', 'Choose spec (2-layer, 1.6mm, HASL)', 'Review design preview before ordering'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['jlcpcb order guide', 'first pcb order checklist'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
  },
  quizzes: {
    'l-elec-basics': [
      {
        id: 'q-ohm1', conceptID: 'c-elec-basics', difficulty: 1,
        prompt: 'What does Ohm\'s Law state?',
        options: [
          { id: 'opt-a', text: 'V = I × R', misconception: undefined },
          { id: 'opt-b', text: 'V = I + R', misconception: 'Confuses sum with product' },
          { id: 'opt-c', text: 'I = V × R', misconception: 'Inverts voltage and current roles' },
          { id: 'opt-d', text: 'R = V + I', misconception: 'Adds instead of divides' },
        ],
        correctOptionID: 'opt-a',
        explanation: 'Ohm\'s Law: Voltage (V) equals Current (I) multiplied by Resistance (R). The most common mistake is confusing it with addition.',
        refBlockID: 'b-hook-elec',
      },
      {
        id: 'q-ohm2', conceptID: 'c-elec-basics', difficulty: 2,
        prompt: 'An LED needs 2V and 20mA from a 5V supply. What resistor value is needed?',
        options: [
          { id: 'opt-e', text: '150Ω', misconception: undefined },
          { id: 'opt-f', text: '250Ω', misconception: 'Used full 5V instead of 3V drop' },
          { id: 'opt-g', text: '100Ω', misconception: 'Subtracted 1V instead of 2V' },
          { id: 'opt-h', text: '300Ω', misconception: 'Doubled the result' },
        ],
        correctOptionID: 'opt-e',
        explanation: 'Voltage drop = 5-2 = 3V. R = 3V/0.020A = 150Ω. The worked example in the lesson covers this step by step.',
        refBlockID: 'b-example-elec',
      },
    ],
  },
  capstone: {
    title: 'Design Your First PCB',
    description: 'Design a complete, functional PCB from scratch — a simple LED blinker or a USB power supply.',
    successCriteria: [
      'Schematic reviewed and ERC passes',
      'PCB layout complete with DRC passing',
      'Gerbers exported and verified in GerbView',
      'Order placed with a PCB fabricator',
    ],
  },
  changelog: [],
};

export const medicalCourseFixture: Course = {
  id: 'demo-medical-course',
  goal: 'Master medical terminology, basic pharmacology, and clinical pathophysiology for effective patient communication',
  profile: {
    topic: 'Medical Terminology & Clinical Basics',
    endArtifact: 'Clinical Patient Care Readiness',
    level: 'beginner',
    hoursPerWeek: 6,
  },
  version: 1,
  concepts: [
    { id: 'c-med-term', name: 'Medical Terminology', summary: 'Learn basic medical language for effective communication.', prereqIDs: [] },
    { id: 'c-pharm-basics', name: 'Pharmacology Basics', summary: 'Core pharmacokinetics, drug categories, and therapeutic effects.', prereqIDs: ['c-med-term'] },
    { id: 'c-anatomy-phys', name: 'Anatomy and Physiology', summary: 'Understand the structure and function of the human body.', prereqIDs: ['c-med-term'] },
    { id: 'c-med-ethics', name: 'Medical Ethics and Professionalism', summary: 'Understand ethical principles and professionalism in healthcare.', prereqIDs: ['c-anatomy-phys'] },
    { id: 'c-disease-patho', name: 'Disease Pathophysiology', summary: 'Study the cellular and molecular basis of common diseases.', prereqIDs: ['c-pharm-basics', 'c-anatomy-phys'] },
  ],
  modules: [
    {
      id: 'm-clinical-foundations',
      title: 'Clinical Foundations',
      outcome: 'Understand anatomical terminology and foundational medical systems',
      lessonIDs: ['l-med-term', 'l-pharm-basics', 'l-anatomy-phys'],
    },
    {
      id: 'm-pathology-ethics',
      title: 'Pathology & Ethics',
      outcome: 'Examine clinical ethics and core disease pathways',
      lessonIDs: ['l-med-ethics', 'l-disease-patho'],
    },
  ],
  lessons: {
    'l-med-term': {
      id: 'l-med-term',
      moduleID: 'm-clinical-foundations',
      title: 'Medical Terminology',
      conceptIDs: ['c-med-term'],
      objectives: [
        'Learn basic medical language for effective communication.',
        'Deconstruct prefixes, word roots, combining vowels, and suffixes',
        'Recognize standard anatomical planes and directional terminology',
      ],
      status: 'ready',
      blocks: [
        {
          type: 'markdown',
          id: 'b-med-intro',
          markdown: '## Decoding Clinical Language\n\nMedical terminology is a systematic language built predominantly from Greek and Latin roots. Understanding how prefixes (location/time), roots (organ/tissue), and suffixes (condition/procedure) assemble allows you to decipher thousands of complex clinical terms instantly.\n\n* **Cardio-** (Heart) + **-ology** (Study of) = Cardiology\n* **Hyper-** (Excessive) + **glyc-** (Sugar) + **-emia** (Blood condition) = Hyperglycemia',
        },
        {
          type: 'workedExample',
          id: 'b-med-example',
          title: 'Deconstructing "Gastroenteritis"',
          steps: [
            { text: 'Identify the word root: "Gastr/o" refers to the stomach.', why: 'Roots designate the primary anatomical structure involved.' },
            { text: 'Identify the secondary root: "Enter/o" refers to the small intestine.', why: 'Compound words often link multiple organs affected together.' },
            { text: 'Analyze the suffix: "-itis" denotes inflammation.', why: 'Standard suffix used across all anatomical pathology.' },
            { text: 'Synthesize the clinical definition: Inflammation of the stomach and small intestine.', why: 'Combining word elements gives unambiguous clinical meaning.' },
          ],
        },
        {
          type: 'callout',
          id: 'b-med-tip',
          kind: 'tip',
          markdown: '**Clinical Tip:** Always read medical terms from the suffix backward to the root and prefix to quickly grasp the diagnosis or procedure.',
        },
        {
          type: 'checkpoint',
          id: 'b-med-check',
          conceptID: 'c-med-term',
          question: 'What does the term "Bradycardia" describe?',
          answer: 'An abnormally slow resting heart rate (< 60 bpm in adults). "Brady-" (slow) + "-cardia" (heart).',
          hint: 'Break the word into the prefix "Brady-" and root "-cardia".',
        },
      ],
      task: {
        title: 'Clinical Chart Vocabulary Audit',
        instructions: [
          'Examine a simulated intake chart note',
          'Highlight and deconstruct 5 unfamiliar medical terms into prefix, root, and suffix',
          'Write plain-language translations suitable for patient communication',
        ],
        successCriteria: [
          'All 5 roots correctly identified',
          'Patient-friendly explanations without medical jargon',
        ],
      },
      resourceQueries: ['medical terminology prefix suffix root guide', 'medical abbreviations clinical practice'],
      resources: [],
      sources: [],
      unsourced: false,
      confidence: 'high',
      version: 1,
    },
    'l-pharm-basics': {
      id: 'l-pharm-basics',
      moduleID: 'm-clinical-foundations',
      title: 'Pharmacology Basics',
      conceptIDs: ['c-pharm-basics'],
      objectives: [
        'Learn basic medical language for effective communication.',
        'Differentiate between pharmacokinetics (ADME) and pharmacodynamics',
        'Identify common therapeutic drug classifications and safety margins',
      ],
      status: 'ready',
      blocks: [
        {
          type: 'markdown',
          id: 'b-pharm-intro',
          markdown: '## Fundamentals of Pharmacology\n\nPharmacology bridges clinical chemistry and human physiology. Every therapeutic intervention relies on two complementary principles:\n\n1. **Pharmacokinetics:** What the body does to the drug (Absorption, Distribution, Metabolism, Excretion — *ADME*).\n2. **Pharmacodynamics:** What the drug does to the body (Receptor agonism/antagonism, biochemical signaling, and therapeutic window).',
        },
        {
          type: 'workedExample',
          id: 'b-pharm-example',
          title: 'Calculating Therapeutic Index (TI)',
          steps: [
            { text: 'Determine Median Lethal Dose (LD50) or Toxic Dose (TD50): 1000 mg.', why: 'Quantifies drug toxicity threshold in trial data.' },
            { text: 'Determine Median Effective Dose (ED50): 100 mg.', why: 'Quantifies dose required to achieve target clinical efficacy.' },
            { text: 'Calculate TI = TD50 / ED50 = 1000 / 100 = 10.', why: 'A higher ratio indicates a broader, safer clinical margin.' },
          ],
        },
        {
          type: 'callout',
          id: 'b-pharm-warning',
          kind: 'warning',
          markdown: '**Safety Alert:** Drugs with a narrow therapeutic index (e.g., Warfarin, Digoxin, Lithium) require continuous serum drug monitoring to prevent toxicity.',
        },
        {
          type: 'checkpoint',
          id: 'b-pharm-check',
          conceptID: 'c-pharm-basics',
          question: 'Which organ is the primary site of drug metabolism via Cytochrome P450 enzymes?',
          answer: 'The Liver (hepatic metabolism).',
          hint: 'Think of the organ responsible for first-pass metabolism.',
        },
      ],
      task: {
        title: 'Medication Reconciliation Simulation',
        instructions: [
          'Review patient medication list for duplicate drug mechanisms',
          'Calculate dosage titration based on renal clearance estimates',
          'Document warning signs for adverse drug-drug interactions',
        ],
        successCriteria: [
          'Metabolic pathways correctly mapped',
          'High-risk interactions flagged with proposed substitutions',
        ],
      },
      resourceQueries: ['pharmacology basics ADME explained', 'drug receptor mechanisms pharmacology'],
      resources: [],
      sources: [],
      unsourced: false,
      confidence: 'high',
      version: 1,
    },
    'l-anatomy-phys': {
      id: 'l-anatomy-phys',
      moduleID: 'm-clinical-foundations',
      title: 'Anatomy and Physiology',
      conceptIDs: ['c-anatomy-phys'],
      objectives: [
        'Understand the structure and function of the human body.',
        'Trace systemic circulation and gas exchange mechanisms',
        'Examine neuromuscular junction signaling and motor unit control',
      ],
      status: 'ready',
      blocks: [
        {
          type: 'markdown',
          id: 'b-anat-intro',
          markdown: '## Systems Architecture of the Human Body\n\nAnatomy explores physical structure; physiology deciphers how those structures sustain life. Homeostatic equilibrium relies on continuous negative feedback loops operating across the cardiovascular, respiratory, renal, and endocrine systems.',
        },
      ],
      task: {
        title: 'Homeostatic Reflex Loop Mapping',
        instructions: [
          'Draw the baroreceptor reflex arc responding to acute orthostatic hypotension',
          'Identify afferent pathway, central integrating center, and efferent targets',
        ],
        successCriteria: ['All 5 reflex arc components accurately sequenced'],
      },
      resourceQueries: ['human anatomy organ systems overview', 'principles of human physiology'],
      resources: [],
      sources: [],
      unsourced: false,
      confidence: 'high',
      version: 1,
    },
    'l-med-ethics': {
      id: 'l-med-ethics',
      moduleID: 'm-pathology-ethics',
      title: 'Medical Ethics and Professionalism',
      conceptIDs: ['c-med-ethics'],
      objectives: [
        'Understand ethical principles and professionalism in healthcare.',
        'Apply the four core biomedical principles: Autonomy, Non-maleficence, Beneficence, and Justice',
        'Navigate patient confidentiality protocols and surrogate decision making',
      ],
      status: 'stub',
      blocks: [],
      resourceQueries: ['biomedical ethics four principles clinical practice', 'patient autonomy informed consent'],
      resources: [],
      sources: [],
      unsourced: true,
      confidence: 'high',
      version: 1,
    },
    'l-disease-patho': {
      id: 'l-disease-patho',
      moduleID: 'm-pathology-ethics',
      title: 'Disease Pathophysiology',
      conceptIDs: ['c-disease-patho'],
      objectives: [
        'Study the cellular and molecular basis of common diseases.',
        'Analyze cellular injury, necrosis vs apoptosis, and vascular response to inflammation',
        'Trace hemodynamic disruptions leading to edema, thrombosis, and shock',
      ],
      status: 'stub',
      blocks: [],
      resourceQueries: ['pathophysiology mechanisms of disease robbins', 'cellular adaptation injury necrosis'],
      resources: [],
      sources: [],
      unsourced: true,
      confidence: 'medium',
      version: 1,
    },
  },
  quizzes: {
    'l-med-term': [
      {
        id: 'q-med-1',
        conceptID: 'c-med-term',
        difficulty: 1,
        prompt: 'Which suffix designates the surgical removal or excision of an organ or tissue?',
        options: [
          { id: 'opt-m1', text: '-ectomy (e.g., Appendectomy)' },
          { id: 'opt-m2', text: '-otomy (e.g., Tracheotomy)', misconception: 'Refers to cutting into/incision, not removal' },
          { id: 'opt-m3', text: '-ostomy (e.g., Colostomy)', misconception: 'Refers to creating an artificial opening' },
          { id: 'opt-m4', text: '-scopy (e.g., Endoscopy)', misconception: 'Refers to visual examination with a scope' },
        ],
        correctOptionID: 'opt-m1',
        explanation: 'The suffix -ectomy denotes surgical excision or removal of a body part.',
      },
      {
        id: 'q-med-2',
        conceptID: 'c-med-term',
        difficulty: 2,
        prompt: 'In anatomical orientation, a structure located closer to the point of attachment or trunk is described as:',
        options: [
          { id: 'opt-m5', text: 'Proximal' },
          { id: 'opt-m6', text: 'Distal', misconception: 'Distal describes a point farther from attachment' },
          { id: 'opt-m7', text: 'Lateral', misconception: 'Lateral describes position away from the midline' },
          { id: 'opt-m8', text: 'Ventral', misconception: 'Ventral refers to the anterior/belly side' },
        ],
        correctOptionID: 'opt-m5',
        explanation: 'Proximal means nearer to the torso or point of limb origin (e.g., the elbow is proximal to the wrist).',
      },
    ],
    'l-pharm-basics': [
      {
        id: 'q-pharm-1',
        conceptID: 'c-pharm-basics',
        difficulty: 1,
        prompt: 'What pharmacokinetic phase describes how a drug passes from site of administration into the bloodstream?',
        options: [
          { id: 'opt-p1', text: 'Absorption' },
          { id: 'opt-p2', text: 'Distribution', misconception: 'Distribution is transport through tissue spaces after absorption' },
          { id: 'opt-p3', text: 'Metabolism', misconception: 'Metabolism is the biochemical biotransformation of the compound' },
          { id: 'opt-p4', text: 'Excretion', misconception: 'Excretion is the elimination of the compound from the body' },
        ],
        correctOptionID: 'opt-p1',
        explanation: 'Absorption governs the rate and extent at which unchanged drug enters systemic circulation.',
      },
    ],
  },
  capstone: {
    title: 'Clinical Case Diagnostic & Care Summary',
    description: 'Synthesize medical terminology, pharmacological mechanisms, and anatomical physiology to deliver an evidence-based diagnostic assessment and patient care protocol.',
    successCriteria: [
      'Accurate deconstruction of clinical signs and medical terminology',
      'Evaluation of primary drug contraindications and metabolic pathways',
      'Integration of ethical patient advocacy and informed consent principles',
    ],
  },
  changelog: [],
};

