// Minimal PCB Course fixture for preview/demo mode
// This is a pre-built course that shows what AnyLearn looks like without an API key.
import type { Course } from './models';

export const pcbCourseFixture: Course = {
  id: 'demo-pcb-course',
  goal: 'I want to learn PCB design from zero and eventually design my own board',
  profile: {
    topic: 'PCB Design',
    endArtifact: 'Working PCB board',
    level: 'beginner',
    hoursPerWeek: 5,
  },
  version: 1,
  concepts: [
    { id: 'c-elec-basics', name: 'Electronic Fundamentals', summary: 'Voltage, current, resistance and Ohm\'s law.', prereqIDs: [] },
    { id: 'c-components', name: 'Basic Components', summary: 'Resistors, capacitors, LEDs, transistors.', prereqIDs: ['c-elec-basics'] },
    { id: 'c-schematic', name: 'Schematic Capture', summary: 'Reading and drawing circuit schematics.', prereqIDs: ['c-components'] },
    { id: 'c-pcb-basics', name: 'PCB Concepts', summary: 'Layers, traces, pads, vias and ground planes.', prereqIDs: ['c-schematic'] },
    { id: 'c-kicad', name: 'KiCad EDA Tool', summary: 'Using KiCad for schematic and PCB layout.', prereqIDs: ['c-pcb-basics'] },
    { id: 'c-layout', name: 'PCB Layout Rules', summary: 'Routing rules, clearances, and design for manufacturing.', prereqIDs: ['c-kicad'] },
    { id: 'c-gerbers', name: 'Gerber Files & Fab', summary: 'Exporting Gerbers and ordering from PCB fabricators.', prereqIDs: ['c-layout'] },
  ],
  modules: [
    {
      id: 'm-foundations',
      title: 'Electronics Foundations',
      outcome: 'Understand electricity and basic components',
      lessonIDs: ['l-elec-basics', 'l-components'],
    },
    {
      id: 'm-schematics',
      title: 'Schematic Design',
      outcome: 'Read and draw circuit schematics confidently',
      lessonIDs: ['l-schematic-reading', 'l-schematic-drawing'],
    },
    {
      id: 'm-pcb-layout',
      title: 'PCB Layout',
      outcome: 'Design a complete PCB layout in KiCad',
      lessonIDs: ['l-pcb-concepts', 'l-kicad-intro', 'l-routing'],
    },
    {
      id: 'm-fabrication',
      title: 'Fabrication & First Board',
      outcome: 'Order and receive your first PCB',
      lessonIDs: ['l-gerbers', 'l-bom', 'l-order'],
    },
  ],
  lessons: {
    'l-elec-basics': {
      id: 'l-elec-basics', moduleID: 'm-foundations',
      title: 'Voltage, Current & Resistance',
      conceptIDs: ['c-elec-basics'],
      objectives: ['Define voltage, current and resistance', 'Apply Ohm\'s law', 'Calculate power dissipation'],
      status: 'ready',
      blocks: [
        { type: 'markdown', id: 'b-hook-elec', markdown: '## Why electronics basics matter\n\nBefore you can design a PCB, you need to understand what\'s flowing through those copper traces. Think of electricity like water: **voltage** is the pressure, **current** is the flow rate, and **resistance** is how narrow the pipe is.' },
        { type: 'workedExample', id: 'b-example-elec', title: 'Calculating LED current', steps: [
          { text: 'Supply voltage: 5V. LED forward voltage: 2V. Desired current: 20mA.', why: 'LEDs need a specific current — too much and they burn out.' },
          { text: 'Voltage across resistor = 5V − 2V = 3V', why: 'The resistor drops whatever voltage the LED doesn\'t need.' },
          { text: 'R = V/I = 3V / 0.020A = 150Ω', why: 'Ohm\'s law gives us the resistor value.' },
        ]},
        { type: 'callout', id: 'b-mistakes-elec', kind: 'mistake', markdown: '**Common mistake:** Forgetting that LED current should be limited with a resistor. Connecting an LED directly to 5V will immediately burn it out.' },
        { type: 'checkpoint', id: 'b-check-elec', conceptID: 'c-elec-basics', question: 'A 12V supply powers a 100Ω resistor. What current flows?', answer: '120mA (I = V/R = 12/100)', hint: 'Use Ohm\'s law: I = V/R' },
      ],
      task: { title: 'Calculate resistor values', instructions: ['Open a simulator (falstad.com/circuit)', 'Build a simple LED circuit with 5V supply', 'Calculate and verify the correct resistor value'], successCriteria: ['LED lights up without burning', 'Correct current measurement'] },
      resourceQueries: ['ohms law explained beginner', 'electronics fundamentals tutorial'],
      resources: [],
      sources: [],
      unsourced: true,
      confidence: 'high',
      version: 1,
    },
    'l-components': {
      id: 'l-components', moduleID: 'm-foundations',
      title: 'Basic Electronic Components',
      conceptIDs: ['c-components'],
      objectives: ['Identify resistors, capacitors, LEDs, and transistors', 'Read component datasheets', 'Choose the right component for a job'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['electronic components explained', 'how to read datasheet beginner'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-schematic-reading': {
      id: 'l-schematic-reading', moduleID: 'm-schematics',
      title: 'Reading Schematics',
      conceptIDs: ['c-schematic'],
      objectives: ['Identify standard schematic symbols', 'Trace signal flow through a circuit', 'Find voltage references and grounds'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['how to read schematic diagram', 'schematic symbols guide'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-schematic-drawing': {
      id: 'l-schematic-drawing', moduleID: 'm-schematics',
      title: 'Drawing Schematics in KiCad',
      conceptIDs: ['c-schematic', 'c-kicad'],
      objectives: ['Create a new schematic project in KiCad', 'Place and wire components', 'Add power symbols and labels'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['kicad schematic tutorial beginner', 'kicad eeschema walkthrough'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-pcb-concepts': {
      id: 'l-pcb-concepts', moduleID: 'm-pcb-layout',
      title: 'PCB Layers & Concepts',
      conceptIDs: ['c-pcb-basics'],
      objectives: ['Explain copper layers, silkscreen, solder mask', 'Define trace, pad, via, and plane', 'Know when to use 2-layer vs 4-layer'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['pcb layer stackup explained', 'what is a via pcb'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-kicad-intro': {
      id: 'l-kicad-intro', moduleID: 'm-pcb-layout',
      title: 'KiCad PCB Editor',
      conceptIDs: ['c-kicad'],
      objectives: ['Navigate the KiCad PCB editor', 'Import netlist from schematic', 'Set board outline and design rules'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['kicad pcb editor tutorial', 'kicad design rules constraints'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-routing': {
      id: 'l-routing', moduleID: 'm-pcb-layout',
      title: 'Routing Traces & Ground Planes',
      conceptIDs: ['c-layout'],
      objectives: ['Route signal traces manually', 'Pour a copper ground plane', 'Verify design rule check passes'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['pcb routing best practices', 'ground plane pour kicad'],
      resources: [], sources: [], unsourced: true, confidence: 'medium', version: 1,
    },
    'l-gerbers': {
      id: 'l-gerbers', moduleID: 'm-fabrication',
      title: 'Exporting Gerber Files',
      conceptIDs: ['c-gerbers'],
      objectives: ['Generate Gerber files from KiCad', 'Verify files with GerbView', 'Prepare manufacturing package'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['export gerber kicad', 'gerber file check viewer'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-bom': {
      id: 'l-bom', moduleID: 'm-fabrication',
      title: 'Bill of Materials (BOM)',
      conceptIDs: ['c-gerbers'],
      objectives: ['Generate BOM from KiCad schematic', 'Source components from LCSC or DigiKey', 'Estimate project cost'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['kicad bom export', 'sourcing electronic components LCSC'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
    'l-order': {
      id: 'l-order', moduleID: 'm-fabrication',
      title: 'Ordering Your First PCB',
      conceptIDs: ['c-gerbers'],
      objectives: ['Upload Gerbers to JLCPCB or PCBWay', 'Choose spec (2-layer, 1.6mm, HASL)', 'Review design preview before ordering'],
      status: 'stub', blocks: [], task: undefined,
      resourceQueries: ['jlcpcb order guide', 'first pcb order checklist'],
      resources: [], sources: [], unsourced: true, confidence: 'high', version: 1,
    },
  },
  quizzes: {
    'l-elec-basics': [
      {
        id: 'q-ohm1', conceptID: 'c-elec-basics', difficulty: 1,
        prompt: 'What does Ohm\'s Law state?',
        options: [
          { id: 'opt-a', text: 'V = I × R', misconception: undefined },
          { id: 'opt-b', text: 'V = I + R', misconception: 'Confuses sum with product' },
          { id: 'opt-c', text: 'I = V × R', misconception: 'Inverts voltage and current roles' },
          { id: 'opt-d', text: 'R = V + I', misconception: 'Adds instead of divides' },
        ],
        correctOptionID: 'opt-a',
        explanation: 'Ohm\'s Law: Voltage (V) equals Current (I) multiplied by Resistance (R). The most common mistake is confusing it with addition.',
        refBlockID: 'b-hook-elec',
      },
      {
        id: 'q-ohm2', conceptID: 'c-elec-basics', difficulty: 2,
        prompt: 'An LED needs 2V and 20mA from a 5V supply. What resistor value is needed?',
        options: [
          { id: 'opt-e', text: '150Ω', misconception: undefined },
          { id: 'opt-f', text: '250Ω', misconception: 'Used full 5V instead of 3V drop' },
          { id: 'opt-g', text: '100Ω', misconception: 'Subtracted 1V instead of 2V' },
          { id: 'opt-h', text: '300Ω', misconception: 'Doubled the result' },
        ],
        correctOptionID: 'opt-e',
        explanation: 'Voltage drop = 5-2 = 3V. R = 3V/0.020A = 150Ω. The worked example in the lesson covers this step by step.',
        refBlockID: 'b-example-elec',
      },
    ],
  },
  capstone: {
    title: 'Design Your First PCB',
    description: 'Design a complete, functional PCB from scratch — a simple LED blinker or a USB power supply.',
    successCriteria: [
      'Schematic reviewed and ERC passes',
      'PCB layout complete with DRC passing',
      'Gerbers exported and verified in GerbView',
      'Order placed with a PCB fabricator',
    ],
  },
  changelog: [],
};
